# Site settings
title: Justin DiRose
email: justin@justindirose.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justindirose.com" # the base hostname & protocol for your site
twitter_username: justindirose
github_username:  justindirose
permalink: none

# Build settings
markdown: kramdown
kramdown:
    input: GFM
timezone: America/Chicago
paginate: 10
sass:
    sass_dir: css
    
# GitHub Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
# Exclusions
exclude: [css/dev/, js/dev, node_modules/, gruntfile.js, package.json, Gemfile, Gemfile.lock]

# Inclusions
include: [assets/, .htacess]
